<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LessonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('lessons')->insert([
            [
                'name' => 'Minna no Nihongo 1',
                'course_id' => 1,
                'number' => 1,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 2',
                'course_id' => 1,
                'number' => 2,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 3',
                'course_id' => 1,
                'number' => 3,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 4',
                'course_id' => 1,
                'number' => 4,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 5',
                'course_id' => 1,
                'number' => 5,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 6',
                'course_id' => 1,
                'number' => 6,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 7',
                'course_id' => 1,
                'number' => 7,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 8',
                'course_id' => 1,
                'number' => 8,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 9',
                'course_id' => 1,
                'number' => 9,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 10',
                'course_id' => 1,
                'number' => 10,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 11',
                'course_id' => 1,
                'number' => 11,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 12',
                'course_id' => 1,
                'number' => 12,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 13',
                'course_id' => 1,
                'number' => 13,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 14',
                'course_id' => 1,
                'number' => 14,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 15',
                'course_id' => 1,
                'number' => 15,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 16',
                'course_id' => 1,
                'number' => 16,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 17',
                'course_id' => 1,
                'number' => 17,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 18',
                'course_id' => 1,
                'number' => 18,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 19',
                'course_id' => 1,
                'number' => 19,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 20',
                'course_id' => 1,
                'number' => 20,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 21',
                'course_id' => 1,
                'number' => 21,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 22',
                'course_id' => 1,
                'number' => 22,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 23',
                'course_id' => 1,
                'number' => 23,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 24',
                'course_id' => 1,
                'number' => 24,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 25',
                'course_id' => 1,
                'number' => 25,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 26',
                'course_id' => 2,
                'number' => 1,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 27',
                'course_id' => 2,
                'number' => 2,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 28',
                'course_id' => 2,
                'number' => 3,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 29',
                'course_id' => 2,
                'number' => 4,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 30',
                'course_id' => 2,
                'number' => 5,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 31',
                'course_id' => 2,
                'number' => 6,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 32',
                'course_id' => 2,
                'number' => 7,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 33',
                'course_id' => 2,
                'number' => 8,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 34',
                'course_id' => 2,
                'number' => 9,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 35',
                'course_id' => 2,
                'number' => 10,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 36',
                'course_id' => 2,
                'number' => 11,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 37',
                'course_id' => 2,
                'number' => 12,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 38',
                'course_id' => 2,
                'number' => 13,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 39',
                'course_id' => 2,
                'number' => 14,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 40',
                'course_id' => 2,
                'number' => 15,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 41',
                'course_id' => 2,
                'number' => 16,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 42',
                'course_id' => 2,
                'number' => 17,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 43',
                'course_id' => 2,
                'number' => 18,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 44',
                'course_id' => 2,
                'number' => 19,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 45',
                'course_id' => 2,
                'number' => 20,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 46',
                'course_id' => 2,
                'number' => 21,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 47',
                'course_id' => 2,
                'number' => 22,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 48',
                'course_id' => 2,
                'number' => 23,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 90',
                'course_id' => 2,
                'number' => 24,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Minna no Nihongo 50',
                'course_id' => 2,
                'number' => 25,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week1 day 1',
                'course_id' => 3,
                'number' => 1,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week1 day 2',
                'course_id' => 3,
                'number' => 2,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week1 day 3',
                'course_id' => 3,
                'number' => 3 ,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week1 day 4',
                'course_id' => 3,
                'number' => 4,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week1 day 5',
                'course_id' => 3,
                'number' => 5,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week1 day 6',
                'course_id' => 3,
                'number' => 6,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week1 day 7',
                'course_id' => 3,
                'number' => 7,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week2 day 1',
                'course_id' => 3,
                'number' => 8,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week2 day 2',
                'course_id' => 3,
                'number' => 9,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week2 day 3',
                'course_id' => 3,
                'number' => 10 ,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week2 day 4',
                'course_id' => 3,
                'number' => 11,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week2 day 5',
                'course_id' => 3,
                'number' => 12,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week2 day 6',
                'course_id' => 3,
                'number' => 13,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week2 day 7',
                'course_id' => 3,
                'number' => 14,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week3 day 1',
                'course_id' => 3,
                'number' => 15,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week3 day 2',
                'course_id' => 3,
                'number' => 16,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week3 day 3',
                'course_id' => 3,
                'number' => 17 ,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week3 day 4',
                'course_id' => 3,
                'number' => 18,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week3 day 5',
                'course_id' => 3,
                'number' => 19,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week3 day 6',
                'course_id' => 3,
                'number' => 20,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week3 day 7',
                'course_id' => 3,
                'number' => 21,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week4 day 1',
                'course_id' => 3,
                'number' => 22,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week4 day 2',
                'course_id' => 3,
                'number' => 23,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week4 day 3',
                'course_id' => 3,
                'number' => 24 ,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week4 day 4',
                'course_id' => 3,
                'number' => 25,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week4 day 5',
                'course_id' => 3,
                'number' => 26,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week4 day 6',
                'course_id' => 3,
                'number' => 27,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week4 day 7',
                'course_id' => 3,
                'number' => 28,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week5 day 1',
                'course_id' => 3,
                'number' => 29,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week5 day 2',
                'course_id' => 3,
                'number' => 30,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week5 day 3',
                'course_id' => 3,
                'number' => 31 ,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week5 day 4',
                'course_id' => 3,
                'number' => 32,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week5 day 5',
                'course_id' => 3,
                'number' => 33,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week5 day 6',
                'course_id' => 3,
                'number' => 34,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week5 day 7',
                'course_id' => 3,
                'number' => 35,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week6 day 1',
                'course_id' => 3,
                'number' => 36,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week6 day 2',
                'course_id' => 3,
                'number' => 37,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week6 day 3',
                'course_id' => 3,
                'number' => 38 ,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week6 day 4',
                'course_id' => 3,
                'number' => 39,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week6 day 5',
                'course_id' => 3,
                'number' => 40,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week6 day 6',
                'course_id' => 3,
                'number' => 41,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week6 day 7',
                'course_id' => 3,
                'number' => 42,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week7 day 1',
                'course_id' => 3,
                'number' => 43,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week7 day 2',
                'course_id' => 3,
                'number' => 44,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week7 day 3',
                'course_id' => 3,
                'number' => 45,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week7 day 4',
                'course_id' => 3,
                'number' => 46,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week7 day 5',
                'course_id' => 3,
                'number' => 47,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week7 day 6',
                'course_id' => 3,
                'number' => 48,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week7 day 7',
                'course_id' => 3,
                'number' => 49,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week8 day 1',
                'course_id' => 3,
                'number' => 50,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week8 day 2',
                'course_id' => 3,
                'number' => 51,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week8 day 3',
                'course_id' => 3,
                'number' => 52 ,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week8 day 4',
                'course_id' => 3,
                'number' => 53,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week8 day 5',
                'course_id' => 3,
                'number' => 54,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week8 day 6',
                'course_id' => 3,
                'number' => 55,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week8 day 7',
                'course_id' => 3,
                'number' => 56,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week1 day 1',
                'course_id' => 4,
                'number' => 1,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week1 day 2',
                'course_id' => 4,
                'number' => 2,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week1 day 3',
                'course_id' => 4,
                'number' => 3 ,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week1 day 4',
                'course_id' => 4,
                'number' => 4,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week1 day 5',
                'course_id' => 4,
                'number' => 5,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week1 day 6',
                'course_id' => 4,
                'number' => 6,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week1 day 7',
                'course_id' => 4,
                'number' => 7,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week2 day 1',
                'course_id' => 4,
                'number' => 8,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week2 day 2',
                'course_id' => 4,
                'number' => 9,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week2 day 3',
                'course_id' => 4,
                'number' => 10 ,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week2 day 4',
                'course_id' => 4,
                'number' => 11,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week2 day 5',
                'course_id' => 4,
                'number' => 12,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week2 day 6',
                'course_id' => 4,
                'number' => 13,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week2 day 7',
                'course_id' => 4,
                'number' => 14,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week3 day 1',
                'course_id' => 4,
                'number' => 15,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week3 day 2',
                'course_id' => 4,
                'number' => 16,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week3 day 3',
                'course_id' => 4,
                'number' => 17 ,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week3 day 4',
                'course_id' => 4,
                'number' => 18,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week3 day 5',
                'course_id' => 4,
                'number' => 19,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week3 day 6',
                'course_id' => 4,
                'number' => 20,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week3 day 7',
                'course_id' => 4,
                'number' => 21,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week4 day 1',
                'course_id' => 4,
                'number' => 22,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week4 day 2',
                'course_id' => 4,
                'number' => 23,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week4 day 3',
                'course_id' => 4,
                'number' => 24 ,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week4 day 4',
                'course_id' => 4,
                'number' => 25,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week4 day 5',
                'course_id' => 4,
                'number' => 26,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week4 day 6',
                'course_id' => 4,
                'number' => 27,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week4 day 7',
                'course_id' => 4,
                'number' => 28,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week5 day 1',
                'course_id' => 4,
                'number' => 29,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week5 day 2',
                'course_id' => 4,
                'number' => 30,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week5 day 3',
                'course_id' => 4,
                'number' => 31 ,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week5 day 4',
                'course_id' => 4,
                'number' => 32,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week5 day 5',
                'course_id' => 4,
                'number' => 33,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week5 day 6',
                'course_id' => 4,
                'number' => 34,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week5 day 7',
                'course_id' => 4,
                'number' => 35,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week6 day 1',
                'course_id' => 4,
                'number' => 36,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week6 day 2',
                'course_id' => 4,
                'number' => 37,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week6 day 3',
                'course_id' => 4,
                'number' => 38 ,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week6 day 4',
                'course_id' => 4,
                'number' => 39,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week6 day 5',
                'course_id' => 4,
                'number' => 40,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week6 day 6',
                'course_id' => 4,
                'number' => 41,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week6 day 7',
                'course_id' => 4,
                'number' => 42,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week7 day 1',
                'course_id' => 4,
                'number' => 43,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week7 day 2',
                'course_id' => 4,
                'number' => 44,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week7 day 3',
                'course_id' => 4,
                'number' => 45,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week7 day 4',
                'course_id' => 4,
                'number' => 46,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week7 day 5',
                'course_id' => 4,
                'number' => 47,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week7 day 6',
                'course_id' => 4,
                'number' => 48,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week7 day 7',
                'course_id' => 4,
                'number' => 49,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week8 day 1',
                'course_id' => 4,
                'number' => 50,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week8 day 2',
                'course_id' => 4,
                'number' => 51,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week8 day 3',
                'course_id' => 4,
                'number' => 52 ,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week8 day 4',
                'course_id' => 4,
                'number' => 53,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week8 day 5',
                'course_id' => 4,
                'number' => 54,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week8 day 6',
                'course_id' => 4,
                'number' => 55,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Soumatome week8 day 7',
                'course_id' => 4,
                'number' => 56,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Shinkanzen master 1',
                'course_id' => 5,
                'number' => 1,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Shinkanzen master 2',
                'course_id' => 5,
                'number' => 2,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Shinkanzen master 3',
                'course_id' => 5,
                'number' => 3,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Shinkanzen master 4',
                'course_id' => 5,
                'number' => 4,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'name' => 'Shinkanzen master 5',
                'course_id' => 5,
                'number' => 5,
                'text_link' => config('constants.text_link'),
                'video_link' => config('constants.video_link'),
                'updated_at' => now(),
                'created_at' => now(),
            ],
        ]);
    }
}
