<?php
return [
    'input_error' => 'ログインに失敗しました。',
    'required'    => 'を入力してください。',
    'email'       => 'を「@」「.」文字など正しく入力してください。',
    'between'     => 'を:min文字以上:max文字以下で入力してください。',
    'max'         => 'を11文字以下で入力してください。',
    'size'        => '写真ファイルを5MB以下のサイズにしてください。',
    'integer'     => 'を半角数字で入力してください。',
    'numeric'     => 'を半角数字で入力してください。',
    'regexNum'    => 'を半角数字で入力してください。',
    'before'      => '年齢(To)は年齢(From)より大きく数字を入力してください。',
    'unique'      => 'が既に登録されています。',
    'max_1'       => 'を:max文字以下で入力してください。',
    'requiredField'      => 'を入力してください。',
    'regex_alphanumeric' => 'を半角英数記号で入力してください。',
    'digits_between'     => 'を11文字以下で入力してください。',
    'after_or_equal'     => '開始日には終了日以前の日付を指定してください。',
    'input_error_student'     => 'Login failed.',
];
